import { Inter } from "next/font/google";
import "./globals.css";
import { useContext } from 'react';
import NavBar from '/src/app/components/navbar.jsx';
import { RouterProvider } from '../app/context/RouterContext';
import { AuthContextProvider } from '../app/context/AuthContext';
import Head from 'next/head';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...rest }) {

  return (
    <html>
      <body className={inter.className}>
        <StoreProvider>
          <AuthContextProvider>
            <RouterProvider>
              {children}
            </RouterProvider>
          </AuthContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
